# fly.toml app configuration file generated for pulse-social on 2023-07-19T09:04:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pulse-social"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
